sudo: false

services:
  - docker

before_script:
  - docker build . --tag=config-migration-tool
  - docker run -e KBC_URL -e KBC_TOKEN config-migration-tool composer ci

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
