app:
  build: .
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: bash -c "composer install && php vendor/bin/phpunit"
  tty: true
  stdin_open: true
  environment:
    KBC_TOKEN: $KBC_TOKEN
    GOOGLE_KEY: $GOOGLE_KEY
    GOOGLE_ACCOUNT_ID: $GOOGLE_ACCOUNT_ID
    GOOGLE_ACCOUNT_EMAIL: $GOOGLE_ACCOUNT_EMAIL
    GOOGLE_ACCESS_TOKEN: $GOOGLE_ACCESS_TOKEN
    GOOGLE_REFRESH_TOKEN: $GOOGLE_REFRESH_TOKEN
