version: "2"
services:
  # for development purposes
  dev:
    build: 
      context: .
    volumes:
      - .:/code
    environment:
      - KBC_TOKEN
      - KBC_URL
      - WR_GOOGLE_DRIVE_ACCOUNT_ID
      - WR_GOOGLE_DRIVE_ACCOUNT_EMAIL
      - WR_GOOGLE_DRIVE_ACCESS_TOKEN
      - WR_GOOGLE_DRIVE_REFRESH_TOKEN
